baseURL = "http://neelparikh.net.s3-website.us-west-2.amazonaws.com/"
languageCode = "en-us"
title = "Neel Parikh"
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
  posts = "/:section/:year/:month/:title/"